//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class VisowFrameWork_UpdateManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(VisowFrameWork.UpdateManager), typeof(VisowFrameWork.ManagerBase));
		L.RegFunction("Prepare", Prepare);
		L.RegFunction("StartGetVersionInfo", StartGetVersionInfo);
		L.RegFunction("StartCheckVersion", StartCheckVersion);
		L.RegFunction("StartDownLoad", StartDownLoad);
		L.RegFunction("StartGame", StartGame);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Prepare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			VisowFrameWork.UpdateManager obj = (VisowFrameWork.UpdateManager)ToLua.CheckObject<VisowFrameWork.UpdateManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.Prepare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartGetVersionInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			VisowFrameWork.UpdateManager obj = (VisowFrameWork.UpdateManager)ToLua.CheckObject<VisowFrameWork.UpdateManager>(L, 1);
			obj.StartGetVersionInfo();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartCheckVersion(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			VisowFrameWork.UpdateManager obj = (VisowFrameWork.UpdateManager)ToLua.CheckObject<VisowFrameWork.UpdateManager>(L, 1);
			obj.StartCheckVersion();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartDownLoad(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			VisowFrameWork.UpdateManager obj = (VisowFrameWork.UpdateManager)ToLua.CheckObject<VisowFrameWork.UpdateManager>(L, 1);
			obj.StartDownLoad();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			VisowFrameWork.UpdateManager obj = (VisowFrameWork.UpdateManager)ToLua.CheckObject<VisowFrameWork.UpdateManager>(L, 1);
			obj.StartGame();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

